//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mainframe_2_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logins
    {
        public int id { get; set; }
        public Nullable<int> owner_id { get; set; }
        public string client_ip { get; set; }
        public System.DateTime occured { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
